In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Análisis exploratorio

In [ ]:
#Carga de datos
df = pd.read_csv('Casos_positivos_de_COVID-19_en_Colombia._20260331.csv')
# dtype={14: str} asigna a la columna 14 el tipo str
#low_memory=False lee todo el archivo antes de interpretar tipos

/tmp/ipykernel_12498/2798256446.py:2: DtypeWarning: Columns (14) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Casos_positivos_de_COVID-19_en_Colombia._20260331.csv')

In [ ]:
#Revisión de columnas
display(df.columns)

#Revisión de tipos de datos
df.dtypes

Index(['fecha reporte web', 'ID de caso', 'Fecha de notificación',
       'Código DIVIPOLA departamento', 'Nombre departamento',
       'Código DIVIPOLA municipio', 'Nombre municipio', 'Edad',
       'Unidad de medida de edad', 'Sexo', 'Tipo de contagio',
       'Ubicación del caso', 'Estado', 'Código ISO del país',
       'Nombre del país', 'Recuperado', 'Fecha de inicio de síntomas',
       'Fecha de muerte', 'Fecha de diagnóstico', 'Fecha de recuperación',
       'Tipo de recuperación', 'Pertenencia étnica',
       'Nombre del grupo étnico'],
      dtype='object')

fecha reporte web                object
ID de caso                       object
Fecha de notificación            object
Código DIVIPOLA departamento    float64
Nombre departamento              object
Código DIVIPOLA municipio       float64
Nombre municipio                 object
Edad                              int64
Unidad de medida de edad          int64
Sexo                             object
Tipo de contagio                 object
Ubicación del caso               object
Estado                           object
Código ISO del país             float64
Nombre del país                  object
Recuperado                       object
Fecha de inicio de síntomas      object
Fecha de muerte                  object
Fecha de diagnóstico             object
Fecha de recuperación            object
Tipo de recuperación             object
Pertenencia étnica              float64
Nombre del grupo étnico          object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6390971 entries, 0 to 6390970
Data columns (total 23 columns):
 #   Column                        Dtype
---  ------                        -----
 0   fecha reporte web             object
 1   ID de caso                    object
 2   Fecha de notificación         object
 3   Código DIVIPOLA departamento  float64
 4   Nombre departamento           object
 5   Código DIVIPOLA municipio     float64
 6   Nombre municipio              object
 7   Edad                          int64
 8   Unidad de medida de edad      int64
 9   Sexo                          object
 10  Tipo de contagio              object
 11  Ubicación del caso            object
 12  Estado                        object
 13  Código ISO del país           float64
 14  Nombre del país               object
 15  Recuperado                    object
 16  Fecha de inicio de síntomas   object
 17  Fecha de muerte               object
 18  Fecha de diagnóstico          object
 19  Fecha de recuperación         object
 20  Tipo de recuperación          object
 21  Pertenencia étnica            float64
 22  Nombre del grupo étnico       object
dtypes: float64(4), int64(2), object(17)
memory usage: 1.1+ GB

In [ ]:
#cambiar notación científica por notación "normal"
pd.set_option('display.float_format', '{:.2f}'.format)
#Regresar a notación cietífica
# pd.set_option('display.float_format', None)
df.describe()

,Código DIVIPOLA departamento,Código DIVIPOLA municipio,Edad,Unidad de medida de edad,Código ISO del país,Pertenencia étnica
count,6390971.00,6390971.00,6390971.00,6390971.00,3710.00,6388815.00
mean,28.36,28.48,39.98,1.01,599.54,5.91
std,26.29,26.31,18.47,0.08,281.79,0.59
min,5.00,5.00,1.00,1.00,1.00,1.00
25%,11.00,11.00,27.00,1.00,388.00,6.00
50%,11.00,11.00,38.00,1.00,724.00,6.00
75%,52.00,52.00,53.00,1.00,840.00,6.00
max,99.00,99.77,114.00,5.00,862.00,6.00

In [ ]:
#Revisión de datos
display(df.head())

df.tail()

,fecha reporte web,ID de caso,Fecha de notificación,Código DIVIPOLA departamento,Nombre departamento,Código DIVIPOLA municipio,Nombre municipio,Edad,Unidad de medida de edad,Sexo,...,Código ISO del país,Nombre del país,Recuperado,Fecha de inicio de síntomas,Fecha de muerte,Fecha de diagnóstico,Fecha de recuperación,Tipo de recuperación,Pertenencia étnica,Nombre del grupo étnico
0,2020-12-24 00:00:00,1.556.979,2020-12-22 00:00:00,76.00,VALLE,76.00,CALI,67,1,F,...,NaN,NaN,Recuperado,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6.00,NaN
1,2020-12-24 00:00:00,1.556.980,2020-12-19 00:00:00,76.00,VALLE,76.00,CALI,66,1,F,...,NaN,NaN,Recuperado,2020-12-07 00:00:00,NaN,2020-12-23 00:00:00,2020-12-25 00:00:00,Tiempo,6.00,NaN
2,2020-12-24 00:00:00,1.556.981,2020-12-19 00:00:00,76.00,VALLE,76.00,CALI,68,1,F,...,NaN,NaN,Recuperado,2020-12-18 00:00:00,NaN,2020-12-22 00:00:00,2021-01-01 00:00:00,Tiempo,6.00,NaN
3,2020-12-24 00:00:00,1.556.982,2020-12-22 00:00:00,76.00,VALLE,76.00,CALI,74,1,F,...,NaN,NaN,Fallecido,2020-12-17 00:00:00,2020-12-30 00:00:00,2020-12-23 00:00:00,NaN,NaN,6.00,NaN
4,2020-12-24 00:00:00,1.556.983,2020-12-22 00:00:00,76.00,VALLE,76.00,CALI,65,1,F,...,NaN,NaN,Recuperado,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6.00,NaN

,fecha reporte web,ID de caso,Fecha de notificación,Código DIVIPOLA departamento,Nombre departamento,Código DIVIPOLA municipio,Nombre municipio,Edad,Unidad de medida de edad,Sexo,...,Código ISO del país,Nombre del país,Recuperado,Fecha de inicio de síntomas,Fecha de muerte,Fecha de diagnóstico,Fecha de recuperación,Tipo de recuperación,Pertenencia étnica,Nombre del grupo étnico
6390966,2021-10-24 00:00:00,4.990.088,2021-10-19 00:00:00,76.00,VALLE,76.52,PALMIRA,37,1,M,...,NaN,NaN,Recuperado,2021-10-13 00:00:00,NaN,2021-10-23 00:00:00,2021-10-27 00:00:00,Tiempo,6.00,NaN
6390967,2021-10-24 00:00:00,4.990.091,2021-10-23 00:00:00,76.00,VALLE,76.52,PALMIRA,36,1,M,...,NaN,NaN,Recuperado,2021-10-16 00:00:00,NaN,2021-10-23 00:00:00,2021-10-30 00:00:00,Tiempo,6.00,NaN
6390968,2021-10-24 00:00:00,4.990.092,2021-10-19 00:00:00,76.00,VALLE,76.36,JAMUNDI,39,1,F,...,NaN,NaN,Recuperado,2021-10-18 00:00:00,NaN,2021-10-23 00:00:00,2021-11-01 00:00:00,Tiempo,6.00,NaN
6390969,2021-10-24 00:00:00,4.990.095,2021-11-05 00:00:00,76.00,VALLE,76.36,JAMUNDI,43,1,F,...,NaN,NaN,Recuperado,2021-10-21 00:00:00,NaN,2021-10-23 00:00:00,2021-11-04 00:00:00,PCR,6.00,NaN
6390970,2021-10-24 00:00:00,4.990.096,2021-10-22 00:00:00,76.00,VALLE,76.36,JAMUNDI,16,1,M,...,NaN,NaN,Recuperado,2021-10-21 00:00:00,NaN,2021-10-23 00:00:00,2021-11-04 00:00:00,PCR,6.00,NaN

In [ ]:
#Cantidad de datos nullos
# display(df.isnull().sum())

#porcentaje de nulos
df.isnull().sum() * 100 / len(df)

fecha reporte web               0.00
ID de caso                      0.00
Fecha de notificación           0.00
Código DIVIPOLA departamento    0.00
Nombre departamento             0.00
Código DIVIPOLA municipio       0.00
Nombre municipio                0.00
Edad                            0.00
Unidad de medida de edad        0.00
Sexo                            0.00
Tipo de contagio                0.00
Ubicación del caso              0.65
Estado                          0.65
Código ISO del país            99.94
Nombre del país                99.94
Recuperado                      0.57
Fecha de inicio de síntomas     7.91
Fecha de muerte                97.11
Fecha de diagnóstico            0.04
Fecha de recuperación           2.85
Tipo de recuperación            2.85
Pertenencia étnica              0.03
Nombre del grupo étnico        98.69
dtype: float64

## Hallazgos iniciales


|campo                  | porcentaje de valores nulos|
|---------------------- |---------- |
|Código ISO del país    |99.941949  |
|Nombre del país	    |99.941824  |
|Nombre del grupo étnico|98.687774  |
|Fecha de muerte	    |97.114789  |


En base a lo visto en el análisis exploratorio, se hallaron 4 columnas que presentan una gran cantidad de valores nulos y un porcentaje superior al 95%. Se opta por eliminar las columnas:

* Código ISO del país
* Nombre del país
* Nombre del grupo étnico

Por la gran cantidad de valores nulos y al ser valores que no afectan el análisis a realizar. La columna Fecha de muerte permanece, ya que esta nos habla directamente de la mejoría de los pacientes.

# Limpieza de datos

In [ ]:
#Generar una copia del DF para trabajar de forma segura
df_clean = df.copy()

In [ ]:
#Consultar la cantidad de registros duplicados
df_clean.duplicated().sum()

np.int64(0)

In [ ]:
#Eliminar las columnas mencionadas en hallazgos iniciales
df_clean.drop(['Código ISO del país', 'Nombre del país', 'Nombre del grupo étnico'], axis=1, inplace=True)

In [ ]:
#Comprobación de la eliminación de las columnas
display(df.shape)
df_clean.shape

(6390971, 23)

(6390971, 20)

In [ ]:
#Verificación tipos de formatos de fecha
df_clean[[
    'fecha reporte web',
    'Fecha de notificación',
    'Fecha de inicio de síntomas',
    'Fecha de muerte',
    'Fecha de diagnóstico',
    'Fecha de recuperación'
    ]]

,fecha reporte web,Fecha de notificación,Fecha de inicio de síntomas,Fecha de muerte,Fecha de diagnóstico,Fecha de recuperación
0,2020-12-24 00:00:00,2020-12-22 00:00:00,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00
1,2020-12-24 00:00:00,2020-12-19 00:00:00,2020-12-07 00:00:00,NaN,2020-12-23 00:00:00,2020-12-25 00:00:00
2,2020-12-24 00:00:00,2020-12-19 00:00:00,2020-12-18 00:00:00,NaN,2020-12-22 00:00:00,2021-01-01 00:00:00
3,2020-12-24 00:00:00,2020-12-22 00:00:00,2020-12-17 00:00:00,2020-12-30 00:00:00,2020-12-23 00:00:00,NaN
4,2020-12-24 00:00:00,2020-12-22 00:00:00,2020-12-21 00:00:00,NaN,2020-12-23 00:00:00,2021-01-04 00:00:00
...,...,...,...,...,...,...
6390966,2021-10-24 00:00:00,2021-10-19 00:00:00,2021-10-13 00:00:00,NaN,2021-10-23 00:00:00,2021-10-27 00:00:00
6390967,2021-10-24 00:00:00,2021-10-23 00:00:00,2021-10-16 00:00:00,NaN,2021-10-23 00:00:00,2021-10-30 00:00:00
6390968,2021-10-24 00:00:00,2021-10-19 00:00:00,2021-10-18 00:00:00,NaN,2021-10-23 00:00:00,2021-11-01 00:00:00
6390969,2021-10-24 00:00:00,2021-11-05 00:00:00,2021-10-21 00:00:00,NaN,2021-10-23 00:00:00,2021-11-04 00:00:00
6390970,2021-10-24 00:00:00,2021-10-22 00:00:00,2021-10-21 00:00:00,NaN,2021-10-23 00:00:00,2021-11-04 00:00:00

In [ ]:
#Conversión a tipo fecha(datetime)
columnas_fecha = [
    'fecha reporte web',
    'Fecha de notificación',
    'Fecha de inicio de síntomas',
    'Fecha de muerte',
    'Fecha de diagnóstico',
    'Fecha de recuperación'
    ]

df_clean[columnas_fecha] = df_clean[columnas_fecha].apply(pd.to_datetime, errors='coerce')

In [ ]:
#Observación del nuevo formato de fecha
df_clean[[
    'fecha reporte web',
    'Fecha de notificación',
    'Fecha de inicio de síntomas',
    'Fecha de muerte',
    'Fecha de diagnóstico',
    'Fecha de recuperación'
    ]]

,fecha reporte web,Fecha de notificación,Fecha de inicio de síntomas,Fecha de muerte,Fecha de diagnóstico,Fecha de recuperación
0,2020-12-24,2020-12-22,2020-12-21,NaT,2020-12-23,2021-01-04
1,2020-12-24,2020-12-19,2020-12-07,NaT,2020-12-23,2020-12-25
2,2020-12-24,2020-12-19,2020-12-18,NaT,2020-12-22,2021-01-01
3,2020-12-24,2020-12-22,2020-12-17,2020-12-30,2020-12-23,NaT
4,2020-12-24,2020-12-22,2020-12-21,NaT,2020-12-23,2021-01-04
...,...,...,...,...,...,...
6390966,2021-10-24,2021-10-19,2021-10-13,NaT,2021-10-23,2021-10-27
6390967,2021-10-24,2021-10-23,2021-10-16,NaT,2021-10-23,2021-10-30
6390968,2021-10-24,2021-10-19,2021-10-18,NaT,2021-10-23,2021-11-01
6390969,2021-10-24,2021-11-05,2021-10-21,NaT,2021-10-23,2021-11-04
6390970,2021-10-24,2021-10-22,2021-10-21,NaT,2021-10-23,2021-11-04

In [ ]:
#Comprobación del nuevo tipo de dato
df_clean.dtypes

fecha reporte web               datetime64[ns]
ID de caso                              object
Fecha de notificación           datetime64[ns]
Código DIVIPOLA departamento           float64
Nombre departamento                     object
Código DIVIPOLA municipio              float64
Nombre municipio                        object
Edad                                     int64
Unidad de medida de edad                 int64
Sexo                                    object
Tipo de contagio                        object
Ubicación del caso                      object
Estado                                  object
Recuperado                              object
Fecha de inicio de síntomas     datetime64[ns]
Fecha de muerte                 datetime64[ns]
Fecha de diagnóstico            datetime64[ns]
Fecha de recuperación           datetime64[ns]
Tipo de recuperación                    object
Pertenencia étnica                     float64
dtype: object

In [ ]:
#Detección de posibles valores duplicados
df_clean.columns
revision_valores_unicos_columnas = ["Sexo", "Ubicación del caso", "Estado", "Recuperado", "Tipo de contagio", 'Tipo de recuperación']

for c in revision_valores_unicos_columnas:
    print(f"{c}: {df_clean[c].unique()}")

Sexo: ['F' 'M' 'f' 'm']
Ubicación del caso: ['Casa' 'Fallecido' nan 'casa' 'CASA' 'Hospital' 'Hospital UCI']
Estado: ['Leve' 'Fallecido' nan 'leve' 'LEVE' 'Moderado' 'Grave']
Recuperado: ['Recuperado' 'Fallecido' nan 'fallecido' 'Activo']
Tipo de contagio: ['Comunitaria' 'Relacionado' 'Importado']
Tipo de recuperación: ['Tiempo' nan 'PCR' 'TIEMPO']

In [ ]:
#Normalización de valores
# Sexo: ['F' 'M' 'f' 'm']
# Ubicación del caso: ['Casa' 'Fallecido' nan 'casa' 'CASA' 'Hospital' 'Hospital UCI']
# Estado: ['Leve' 'Fallecido' nan 'leve' 'LEVE' 'Moderado' 'Grave']
# Recuperado: ['Recuperado' 'Fallecido' nan 'fallecido' 'Activo']
# Tipo de contagio: ['Comunitaria' 'Relacionado' 'Importado']
# Tipo de recuperación: ['Tiempo' nan 'PCR' 'TIEMPO']

reemplazos = {
    'Sexo': {
        'f': 'F',
        'm': 'M'
        },
    'Ubicación del caso': {
        'casa': 'Casa',
        'fallecido': 'Fallecido',
        'hospital': 'Hospital',
        'hospital uci': 'Hospital UCI'
    },
    'Estado': {
        'leve': 'Leve',
        'fallecido': 'Fallecido',
        'moderado': 'Moderado',
        'grave': 'Grave'
    },
    'Recuperado': {
        'recuperado': 'Recuperado',
        'fallecido': 'Fallecido',
        'activo': 'Activo'
    },
    'Tipo de recuperación': {
        'tiempo': 'Tiempo',
        'pcr': 'PCR'
    }
}

for key, value in reemplazos.items():
#items() regresa una tupla de clave:valor a diferencia de values que regresa solo los valores y keys que solo me da la clave
    df_clean[key] = df_clean[key].str.strip().str.lower().replace(value, regex=False)

In [ ]:
# validación corrección de los valores unicos
revision_valores_unicos_columnas = ["Sexo", "Ubicación del caso", "Estado", "Recuperado", "Tipo de contagio", 'Tipo de recuperación']

for c in revision_valores_unicos_columnas:
    print(f"{c}: {df_clean[c].unique()}")

Sexo: ['F' 'M']
Ubicación del caso: ['Casa' 'Fallecido' nan 'Hospital' 'Hospital UCI']
Estado: ['Leve' 'Fallecido' nan 'Moderado' 'Grave']
Recuperado: ['Recuperado' 'Fallecido' nan 'Activo']
Tipo de contagio: ['Comunitaria' 'Relacionado' 'Importado']
Tipo de recuperación: ['Tiempo' nan 'PCR']

In [ ]:
#Validación de nullos
df_clean.isnull().sum()

fecha reporte web                     0
ID de caso                            0
Fecha de notificación                 0
Código DIVIPOLA departamento          0
Nombre departamento                   0
Código DIVIPOLA municipio             0
Nombre municipio                      0
Edad                                  0
Unidad de medida de edad              0
Sexo                                  0
Tipo de contagio                      0
Ubicación del caso                41268
Estado                            41268
Recuperado                        36327
Fecha de inicio de síntomas      505384
Fecha de muerte                 6206578
Fecha de diagnóstico               2755
Fecha de recuperación            182324
Tipo de recuperación             182398
Pertenencia étnica                 2156
dtype: int64

## Relación de valores nulos con fallecimientos

In [ ]:
df_clean['Ubicación del caso'].unique()

array(['Casa', 'Fallecido', 'Hospital', 'Hospital UCI'], dtype=object)

In [ ]:
# Ubicación del caso: ['Casa' 'Fallecido' nan 'Hospital' 'Hospital UCI']
display(df_clean.loc[(df_clean['Ubicación del caso'].isna()) & (df_clean['Fecha de muerte'].isnull())])

#Reemplazo de nulos
df_clean['Ubicación del caso'] = df_clean['Ubicación del caso'].fillna('Fallecido')

# df_clean.fillna({'Ubicación del caso': 'Fallecido'}, inplace=True)

Empty DataFrame
Columns: [fecha reporte web, ID de caso, Fecha de notificación, Código DIVIPOLA departamento, Nombre departamento, Código DIVIPOLA municipio, Nombre municipio, Edad, Unidad de medida de edad, Sexo, Tipo de contagio, Ubicación del caso, Estado, Recuperado, Fecha de inicio de síntomas, Fecha de muerte, Fecha de diagnóstico, Fecha de recuperación, Tipo de recuperación, Pertenencia étnica]
Index: []

In [ ]:
#confirmación del reemplazo exitoso
df_clean['Ubicación del caso'].unique()

array(['Casa', 'Fallecido', 'Hospital', 'Hospital UCI'], dtype=object)

In [ ]:
# Estado: ['Leve' 'Fallecido' nan 'Moderado' 'Grave']
display(df_clean.loc[(df_clean['Estado'].isnull()) & (df_clean['Fecha de muerte'].isnull())])

#Reemplazo de nulos
df_clean['Estado'] = df_clean['Estado'].fillna('Fallecido')

Empty DataFrame
Columns: [fecha reporte web, ID de caso, Fecha de notificación, Código DIVIPOLA departamento, Nombre departamento, Código DIVIPOLA municipio, Nombre municipio, Edad, Unidad de medida de edad, Sexo, Tipo de contagio, Ubicación del caso, Estado, Recuperado, Fecha de inicio de síntomas, Fecha de muerte, Fecha de diagnóstico, Fecha de recuperación, Tipo de recuperación, Pertenencia étnica]
Index: []

In [ ]:
# Confirmación reemplazo exitoso
df_clean['Estado'].unique()

array(['Leve', 'Fallecido', 'Moderado', 'Grave'], dtype=object)

In [ ]:
# Recuperado: ['Recuperado' 'Fallecido' nan 'Activo']

display(df_clean.loc[(df_clean['Fecha de muerte'].notnull())])

# df_clean['Recuperado'] = df_clean['Recuperado'].fillna('Fallecido')

,fecha reporte web,ID de caso,Fecha de notificación,Código DIVIPOLA departamento,Nombre departamento,Código DIVIPOLA municipio,Nombre municipio,Edad,Unidad de medida de edad,Sexo,Tipo de contagio,Ubicación del caso,Estado,Recuperado,Fecha de inicio de síntomas,Fecha de muerte,Fecha de diagnóstico,Fecha de recuperación,Tipo de recuperación,Pertenencia étnica
3,2020-12-24,1.556.982,2020-12-22,76.00,VALLE,76.00,CALI,74,1,F,Comunitaria,Fallecido,Fallecido,Fallecido,2020-12-17,2020-12-30,2020-12-23,NaT,NaN,6.00
7,2020-12-24,1.556.986,2020-12-18,76.00,VALLE,76.00,CALI,66,1,F,Comunitaria,Fallecido,Fallecido,Fallecido,2020-12-11,2020-12-26,2020-12-22,NaT,NaN,6.00
21,2020-11-08,1.137.434,2020-11-05,11.00,BOGOTA,11.00,BOGOTA,81,1,F,Relacionado,Fallecido,Fallecido,Fallecido,2020-10-31,2020-11-11,2020-11-07,NaT,NaN,6.00
30,2020-11-08,1.137.440,2020-11-03,63.00,QUINDIO,63.00,ARMENIA,85,1,F,Comunitaria,Fallecido,Fallecido,Fallecido,2020-10-31,2020-11-12,2020-10-31,NaT,NaN,6.00
33,2020-11-08,1.137.443,2020-11-04,11.00,BOGOTA,11.00,BOGOTA,78,1,M,Comunitaria,Fallecido,Fallecido,Fallecido,2020-10-31,2020-11-16,2020-11-07,NaT,NaN,6.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6390871,2021-09-10,4.926.172,2021-09-08,76.00,VALLE,76.83,TULUA,85,1,M,Comunitaria,Fallecido,Fallecido,Fallecido,2021-09-02,2021-09-25,2021-09-08,NaT,NaN,6.00
6390893,2021-09-10,4.926.122,2021-08-23,5.00,ANTIOQUIA,5.00,MEDELLIN,79,1,F,Relacionado,Fallecido,Fallecido,Fallecido,2021-08-21,2021-11-13,2021-09-08,NaT,NaN,6.00
6390909,2022-01-23,5.715.426,2022-01-20,73.00,TOLIMA,73.00,IBAGUE,77,1,F,Relacionado,Fallecido,Fallecido,Fallecido,2022-01-17,2022-02-05,2022-01-22,NaT,NaN,6.00
6390937,2021-10-24,4.990.109,2021-10-23,76.00,VALLE,76.83,TULUA,81,1,M,Relacionado,Fallecido,Fallecido,Fallecido,2021-10-17,2021-10-27,2021-10-23,NaT,NaN,6.00
6390942,2021-10-24,4.990.117,2021-10-22,76.00,VALLE,76.83,TULUA,53,1,M,Comunitaria,Fallecido,Fallecido,Fallecido,2021-10-16,2021-11-03,2021-10-22,NaT,NaN,6.00

In [ ]:
# Confirmación reemplazo exitoso
df_clean['Recuperado'].unique()

array(['Recuperado', 'Fallecido', 'Activo'], dtype=object)

##Hallazgo
Todos los registros ubicados en las columnas:
* Ubicación del caso
* Estado
* Recuperado
* Tipo de recuperación

Que presentan un valor NaN tienen "Fecha de muerte" no nula, por lo tanto se imputa el valor "Fallecido" en estas columnas

## Eliminación de columnas faltantes

In [ ]:
df_clean.drop(['Código DIVIPOLA departamento', 'Código DIVIPOLA municipio', 'Unidad de medida de edad', 'Pertenencia étnica'], axis=1, inplace=True)
# df_clean = df_clean.drop(['Código DIVIPOLA departamento', 'Código DIVIPOLA municipio', 'Unidad de medida de edad', 'Pertenencia étnica'], axis=1)

In [ ]:
df_clean

,fecha reporte web,ID de caso,Fecha de notificación,Nombre departamento,Nombre municipio,Edad,Sexo,Tipo de contagio,Ubicación del caso,Estado,Recuperado,Fecha de inicio de síntomas,Fecha de muerte,Fecha de diagnóstico,Fecha de recuperación,Tipo de recuperación
0,2020-12-24,1.556.979,2020-12-22,VALLE,CALI,67,F,Comunitaria,Casa,Leve,Recuperado,2020-12-21,NaT,2020-12-23,2021-01-04,Tiempo
1,2020-12-24,1.556.980,2020-12-19,VALLE,CALI,66,F,Comunitaria,Casa,Leve,Recuperado,2020-12-07,NaT,2020-12-23,2020-12-25,Tiempo
2,2020-12-24,1.556.981,2020-12-19,VALLE,CALI,68,F,Comunitaria,Casa,Leve,Recuperado,2020-12-18,NaT,2020-12-22,2021-01-01,Tiempo
3,2020-12-24,1.556.982,2020-12-22,VALLE,CALI,74,F,Comunitaria,Fallecido,Fallecido,Fallecido,2020-12-17,2020-12-30,2020-12-23,NaT,NaN
4,2020-12-24,1.556.983,2020-12-22,VALLE,CALI,65,F,Comunitaria,Casa,Leve,Recuperado,2020-12-21,NaT,2020-12-23,2021-01-04,Tiempo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6390966,2021-10-24,4.990.088,2021-10-19,VALLE,PALMIRA,37,M,Relacionado,Casa,Leve,Recuperado,2021-10-13,NaT,2021-10-23,2021-10-27,Tiempo
6390967,2021-10-24,4.990.091,2021-10-23,VALLE,PALMIRA,36,M,Comunitaria,Casa,Leve,Recuperado,2021-10-16,NaT,2021-10-23,2021-10-30,Tiempo
6390968,2021-10-24,4.990.092,2021-10-19,VALLE,JAMUNDI,39,F,Comunitaria,Casa,Leve,Recuperado,2021-10-18,NaT,2021-10-23,2021-11-01,Tiempo
6390969,2021-10-24,4.990.095,2021-11-05,VALLE,JAMUNDI,43,F,Relacionado,Casa,Leve,Recuperado,2021-10-21,NaT,2021-10-23,2021-11-04,PCR
6390970,2021-10-24,4.990.096,2021-10-22,VALLE,JAMUNDI,16,M,Relacionado,Casa,Leve,Recuperado,2021-10-21,NaT,2021-10-23,2021-11-04,PCR

# Guardado de los datos

### Se dejan algunos errores para su posterior limpieza desde Power Query como:
1. Valores vacios en fecha de inicio de sintomas
2. Se dejan valores nulos en la columna de Tipo de recuperación para su posterior transformación (reemplazo)

In [ ]:
df_clean.to_csv('casos_positivos_COVID_limpio.csv', index=False)

# Revisión de datos antes de limpieza en Power Query

In [ ]:
df = pd.read_csv('casos_positivos_COVID_limpio.csv')

In [ ]:
revision_valores_unicos_columnas = ["Sexo", "Ubicación del caso", "Estado", "Recuperado", "Tipo de contagio", 'Tipo de recuperación']

In [ ]:
filtrado_fecha_inicio_sintimas_null = df[df['Fecha de inicio de síntomas'].isnull()]

print("inicio de sintomas nulo")
for c in revision_valores_unicos_columnas:
    print(f"{c}:",filtrado_fecha_inicio_sintimas_null[c].unique())

print("\n")

print("dataset general")
for c in revision_valores_unicos_columnas:
    print(f"{c}:",df[c].unique())

inicio de sintomas nulo
Sexo: ['M' 'F']
Ubicación del caso: ['Casa' 'Fallecido']
Estado: ['Leve' 'Fallecido']
Recuperado: ['Recuperado' 'Fallecido' 'Activo']
Tipo de contagio: ['Relacionado' 'Comunitaria' 'Importado']
Tipo de recuperación: ['PCR' 'Tiempo' nan]


dataset general
Sexo: ['F' 'M']
Ubicación del caso: ['Casa' 'Fallecido' 'Hospital' 'Hospital UCI']
Estado: ['Leve' 'Fallecido' 'Moderado' 'Grave']
Recuperado: ['Recuperado' 'Fallecido' 'Activo']
Tipo de contagio: ['Comunitaria' 'Relacionado' 'Importado']
Tipo de recuperación: ['Tiempo' nan 'PCR']

Luego de la revisión anterior se determina que las filas con valor nulo en la columna de fecha inicio de síntomas no pueden ser omitidos debido a que se perdería integridad de los datos al perderse diversos valores de las columnas:
* Ubicación
* Estado

In [ ]:
df['Fecha de diagnóstico'].isnull().sum()

np.int64(2755)

 # Corroboraciones durante la graficación

In [ ]:
df_clean['Tipo de contagio'].value_counts()

Tipo de contagio
Comunitaria    4447740
Relacionado    1939528
Importado         3703
Name: count, dtype: int64

In [ ]:
df_clean['Fecha de recuperación'].isna().value_counts()

# [
#     'fecha reporte web', no nulos 344622 nulos 0
#     'Fecha de notificación',no nulos 344622 nulos 0
#     'Fecha de inicio de síntomas', #no nulos 316821 nulos 	27801
#     'Fecha de diagnóstico', # no nulos 344351 nulos 27
#     ]

Fecha de recuperación
False    6208647
True      182324
Name: count, dtype: int64

In [ ]:
df_clean[(df_clean['Estado'].isnull()) & (df_clean['Fecha de muerte'].isnull())]

Empty DataFrame
Columns: [fecha reporte web, ID de caso, Fecha de notificación, Nombre departamento, Nombre municipio, Edad, Sexo, Tipo de contagio, Ubicación del caso, Estado, Recuperado, Fecha de inicio de síntomas, Fecha de muerte, Fecha de diagnóstico, Fecha de recuperación, Tipo de recuperación]
Index: []

In [ ]:
df_clean[(df_clean['Recuperado'].isna()) & (df_clean['Fecha de muerte'].isna())]

Empty DataFrame
Columns: [fecha reporte web, ID de caso, Fecha de notificación, Nombre departamento, Nombre municipio, Edad, Sexo, Tipo de contagio, Ubicación del caso, Estado, Recuperado, Fecha de inicio de síntomas, Fecha de muerte, Fecha de diagnóstico, Fecha de recuperación, Tipo de recuperación]
Index: []

In [ ]:
df_clean[df_clean['Fecha de inicio de síntomas'].isnull()]

,fecha reporte web,ID de caso,Fecha de notificación,Nombre departamento,Nombre municipio,Edad,Sexo,Tipo de contagio,Ubicación del caso,Estado,Recuperado,Fecha de inicio de síntomas,Fecha de muerte,Fecha de diagnóstico,Fecha de recuperación,Tipo de recuperación
156,2021-09-19,4.939.862,2021-05-23,BOGOTA,BOGOTA,59,M,Relacionado,Casa,Leve,Recuperado,NaT,NaT,2021-05-26,2021-09-17,PCR
173,2021-09-20,4.941.723,2021-09-17,BOGOTA,BOGOTA,28,F,Comunitaria,Casa,Leve,Recuperado,NaT,NaT,2021-09-18,2021-10-01,Tiempo
252,2021-01-14,1.841.872,2021-01-07,BOGOTA,BOGOTA,30,M,Comunitaria,Casa,Leve,Recuperado,NaT,NaT,2021-01-12,2021-01-25,Tiempo
271,2021-01-14,1.841.885,2021-01-08,BOGOTA,BOGOTA,28,M,Relacionado,Casa,Leve,Recuperado,NaT,NaT,2021-01-13,2021-01-25,Tiempo
272,2021-01-14,1.841.886,2021-01-08,BOGOTA,BOGOTA,31,M,Comunitaria,Casa,Leve,Recuperado,NaT,NaT,2021-01-13,2021-01-25,Tiempo
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
344553,2021-04-18,2.640.812,2021-04-17,BOGOTA,BOGOTA,35,F,Comunitaria,Casa,Leve,Recuperado,NaT,NaT,2021-04-17,2021-04-22,PCR
344562,2021-04-18,2.640.821,2021-04-15,BOGOTA,BOGOTA,44,F,Relacionado,Casa,Leve,Recuperado,NaT,NaT,2021-04-16,2021-04-20,PCR
344564,2021-04-18,2.640.823,2021-04-16,BOGOTA,BOGOTA,50,F,Comunitaria,Casa,Leve,Recuperado,NaT,NaT,2021-04-16,2021-04-30,Tiempo
344565,2021-04-18,2.640.824,2021-04-14,BOGOTA,BOGOTA,61,F,Relacionado,Casa,Leve,Recuperado,NaT,NaT,2021-04-16,2021-04-28,Tiempo
344596,2021-04-18,2.640.786,2021-04-15,BOGOTA,BOGOTA,48,F,Relacionado,Casa,Leve,Recuperado,NaT,NaT,2021-04-17,2021-04-29,Tiempo